version: '2'

services:
  app:
    build: .
    image: blind-test-api
    command: amber watch
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/blind_test_api_development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - shards:/app/lib

  migrate:
    build: .
    image: blind-test-api
    command: bash -c 'while ! nc -q 1 db 5432 </dev/null; do sleep 1; done && amber db migrate seed'
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/blind_test_api_development
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blind_test_api_development
    volumes:
      - db:/var/lib/postgres/data

  spec:
    build: .
    image: app
    command: bash -c "crystal tool format --check && crystal spec"
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/blind_test_api_development
    volumes:
      - .:/app
      - shards:/app/lib
    links:
      - db

volumes:
  db:
  shards:
