secret_key_base: 7WWTVqlKTW3QVFcYFecAKzkKT2hOoyZD_N2peAgvvfI
port: 3000
name: blind-test-api

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - password_confirmation
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
auto_reload: false
database_url: postgres://postgres:@localhost:5432/blind_test_api_test

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
